name: s3adnet

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python = 3.8
  - pytorch = 1.8
  - pandas = 1.2
  - scipy = 1.7
  - numpy = 1.21
  - scikit-learn = 1.0
  - torchmetrics = 0.5
  - tensorboard = 2.6
  - pytorch-lightning = 1.3
  - tqdm = 4.62
